# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start_Dialog(object):
    def setupUi(self, Start_Dialog):
        Start_Dialog.setObjectName("Start_Dialog")
        Start_Dialog.resize(511, 431)
        self.lbl_info = QtWidgets.QLabel(Start_Dialog)
        self.lbl_info.setGeometry(QtCore.QRect(40, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_info.setFont(font)
        self.lbl_info.setObjectName("lbl_info")
        self.txtArea_info = QtWidgets.QPlainTextEdit(Start_Dialog)
        self.txtArea_info.setGeometry(QtCore.QRect(160, 160, 326, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtArea_info.sizePolicy().hasHeightForWidth())
        self.txtArea_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtArea_info.setFont(font)
        self.txtArea_info.setObjectName("txtArea_info")
        self.lbl_amount = QtWidgets.QLabel(Start_Dialog)
        self.lbl_amount.setGeometry(QtCore.QRect(310, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_amount.setFont(font)
        self.lbl_amount.setObjectName("lbl_amount")
        self.txt_type = QtWidgets.QLineEdit(Start_Dialog)
        self.txt_type.setGeometry(QtCore.QRect(160, 20, 321, 39))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_type.setFont(font)
        self.txt_type.setObjectName("txt_type")
        self.lbl_type = QtWidgets.QLabel(Start_Dialog)
        self.lbl_type.setGeometry(QtCore.QRect(30, 20, 122, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_type.setFont(font)
        self.lbl_type.setObjectName("lbl_type")
        self.txt_pieces = QtWidgets.QLineEdit(Start_Dialog)
        self.txt_pieces.setGeometry(QtCore.QRect(160, 90, 91, 39))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_pieces.setFont(font)
        self.txt_pieces.setText("")
        self.txt_pieces.setObjectName("txt_pieces")
        self.txt_amount = QtWidgets.QLineEdit(Start_Dialog)
        self.txt_amount.setGeometry(QtCore.QRect(400, 90, 81, 39))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_amount.setFont(font)
        self.txt_amount.setText("")
        self.txt_amount.setObjectName("txt_amount")
        self.lb_pieces = QtWidgets.QLabel(Start_Dialog)
        self.lb_pieces.setGeometry(QtCore.QRect(90, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_pieces.setFont(font)
        self.lb_pieces.setObjectName("lb_pieces")
        self.btn_Start_P = QtWidgets.QPushButton(Start_Dialog)
        self.btn_Start_P.setEnabled(True)
        self.btn_Start_P.setGeometry(QtCore.QRect(120, 290, 271, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Start_P.sizePolicy().hasHeightForWidth())
        self.btn_Start_P.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_Start_P.setFont(font)
        self.btn_Start_P.setIconSize(QtCore.QSize(32, 32))
        self.btn_Start_P.setObjectName("btn_Start_P")

        self.retranslateUi(Start_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Start_Dialog)
        Start_Dialog.setTabOrder(self.txt_type, self.txt_pieces)
        Start_Dialog.setTabOrder(self.txt_pieces, self.txt_amount)
        Start_Dialog.setTabOrder(self.txt_amount, self.txtArea_info)
        Start_Dialog.setTabOrder(self.txtArea_info, self.btn_Start_P)

    def retranslateUi(self, Start_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Start_Dialog.setWindowTitle(_translate("Start_Dialog", "Ürün Bilgisi"))
        self.lbl_info.setText(_translate("Start_Dialog", "Açıklama:"))
        self.lbl_amount.setText(_translate("Start_Dialog", "M³:"))
        self.lbl_type.setText(_translate("Start_Dialog", "Ürün Cinsi:"))
        self.lb_pieces.setText(_translate("Start_Dialog", "Adet:"))
        self.btn_Start_P.setText(_translate("Start_Dialog", "Başlat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Start_Dialog = QtWidgets.QDialog()
    ui = Ui_Start_Dialog()
    ui.setupUi(Start_Dialog)
    Start_Dialog.show()
    sys.exit(app.exec_())
